.PHONY:all

#syntax: $(strip _string)
#delte the exstral space

original = foo.c                  bar.c
stripped := $(strip $(original))

all:
	@echo "original = $(original)"
	@echo "stripped = $(stripped)"
